spring.application.name=chillywatts

# Configuracao do banco H2
# MySQL
spring.datasource.url=jdbc:mysql://db:3306/chillywatts_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.h2.console.path=/h2-console
# spring.h2.console.enabled=true
#spring.jpa.defer-datasource-initialization=true